# Generated by Django 3.2.7 on 2021-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='d', upload_to=''),
            preserve_default=False,
        ),
    ]
