# Generated by Django 3.2.7 on 2021-11-11 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_project_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.portfolio'),
        ),
    ]
