# Generated by Django 3.2.7 on 2021-11-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211114_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.URLField(),
        ),
    ]
